import React, { useEffect, useState } from 'react';
import {
  View, Text, ScrollView, StyleSheet, Platform,
  TouchableOpacity, ActivityIndicator, Share, Alert,
} from 'react-native';
import { loadProfile } from '../storage/profileStorage';

function QRDisplay({ data }) {
  if (Platform.OS === 'web') {
    const encoded = encodeURIComponent(data);
    const src = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encoded}`;
    return (
      <img src={src} alt="Emergency QR Code" width={220} height={220} style={{ borderRadius: 8 }} />
    );
  }
  const QRCode = require('react-native-qrcode-svg').default;
  return <QRCode value={data} size={220} />;
}

function buildShareText(profile) {
  const lines = ['🚑 EMERGENCY MEDICAL CARD — MediScan', ''];
  if (profile.name)               lines.push(`Name: ${profile.name}`);
  if (profile.bloodGroup)         lines.push(`Blood group: ${profile.bloodGroup} ⚠️`);
  if (profile.drugAllergies.length)  lines.push(`Drug allergies: ${profile.drugAllergies.join(', ')} ⚠️`);
  if (profile.foodAllergies.length)  lines.push(`Food allergies: ${profile.foodAllergies.join(', ')}`);
  if (profile.medications.length)    lines.push(`Medications: ${profile.medications.join(', ')}`);
  if (profile.conditions.length)     lines.push(`Conditions: ${profile.conditions.join(', ')}`);
  if (profile.emergencyContacts.length) {
    lines.push('');
    lines.push('Emergency contacts:');
    profile.emergencyContacts.forEach((c) => lines.push(`  • ${c}`));
  }
  lines.push('');
  lines.push('Generated by MediScan — medicine-bot.vercel.app');
  return lines.join('\n');
}

export default function EmergencyScreen() {
  const [profile, setProfile]   = useState(null);
  const [sharing, setSharing]   = useState(false);
  const [copied,  setCopied]    = useState(false);

  useEffect(() => { loadProfile().then(setProfile); }, []);

  if (!profile) {
    return <View style={styles.loading}><ActivityIndicator size="large" color="#DC2626" /></View>;
  }

  const emergencyData = JSON.stringify({
    name: profile.name,
    bloodGroup: profile.bloodGroup,
    drugAllergies: profile.drugAllergies,
    foodAllergies: profile.foodAllergies,
    medications: profile.medications,
    conditions: profile.conditions,
    emergencyContacts: profile.emergencyContacts,
  });

  const hasData =
    profile.bloodGroup ||
    profile.drugAllergies.length > 0 ||
    profile.conditions.length > 0;

  const shareText = buildShareText(profile);

  async function handleShare() {
    if (Platform.OS === 'web') {
      // Web: copy to clipboard
      try {
        await navigator.clipboard.writeText(shareText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
      } catch {
        Alert.alert('Could not copy', 'Please copy the text manually.');
      }
      return;
    }
    // Native: use Share sheet
    setSharing(true);
    try {
      await Share.share({ message: shareText, title: 'My Emergency Medical Card' });
    } catch (e) {
      console.error(e);
    } finally {
      setSharing(false);
    }
  }

  async function handleCopyJSON() {
    if (Platform.OS === 'web') {
      try {
        await navigator.clipboard.writeText(emergencyData);
        Alert.alert('Copied', 'Emergency data JSON copied to clipboard.');
      } catch { /* ignore */ }
    }
  }

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerBadge}>
          <Text style={styles.headerIcon}>🚑</Text>
        </View>
        <Text style={styles.heading}>Emergency card</Text>
        <Text style={styles.subheading}>Show this to first responders</Text>
      </View>

      {!hasData ? (
        <View style={styles.emptyBox}>
          <Text style={styles.emptyIcon}>📋</Text>
          <Text style={styles.emptyTitle}>Profile is empty</Text>
          <Text style={styles.emptyText}>
            Fill in your blood group, allergies and conditions in the Profile tab to generate your emergency card.
          </Text>
        </View>
      ) : (
        <>
          {/* Critical alerts strip */}
          {(profile.bloodGroup || profile.drugAllergies.length > 0) && (
            <View style={styles.criticalStrip}>
              {profile.bloodGroup && (
                <View style={styles.criticalPill}>
                  <Text style={styles.criticalPillText}>🩸 {profile.bloodGroup}</Text>
                </View>
              )}
              {profile.drugAllergies.map((a, i) => (
                <View key={i} style={styles.criticalPill}>
                  <Text style={styles.criticalPillText}>⚠️ {a}</Text>
                </View>
              ))}
            </View>
          )}

          {/* Info table */}
          <View style={styles.summaryBox}>
            {profile.name         ? <Row label="Name"               value={profile.name} /> : null}
            {profile.bloodGroup   ? <Row label="Blood group"        value={profile.bloodGroup} critical /> : null}
            {profile.drugAllergies.length > 0 && (
              <Row label="Drug allergies"   value={profile.drugAllergies.join(', ')} critical />
            )}
            {profile.foodAllergies.length > 0 && (
              <Row label="Food allergies"   value={profile.foodAllergies.join(', ')} />
            )}
            {profile.medications.length > 0 && (
              <Row label="Medications"      value={profile.medications.join(', ')} />
            )}
            {profile.conditions.length > 0 && (
              <Row label="Conditions"       value={profile.conditions.join(', ')} />
            )}
            {profile.emergencyContacts.length > 0 && (
              <Row label="Emergency contacts" value={profile.emergencyContacts.join('\n')} />
            )}
          </View>

          {/* Share buttons */}
          <View style={styles.shareRow}>
            <TouchableOpacity
              style={[styles.shareBtn, styles.shareBtnPrimary, sharing && styles.shareBtnDisabled]}
              onPress={handleShare}
              disabled={sharing}
            >
              {sharing
                ? <ActivityIndicator color="#fff" size="small" />
                : <Text style={styles.shareBtnText}>
                    {Platform.OS === 'web'
                      ? (copied ? '✅ Copied!' : '📋 Copy card')
                      : '📤 Share card'}
                  </Text>
              }
            </TouchableOpacity>

            {Platform.OS === 'web' && (
              <TouchableOpacity style={[styles.shareBtn, styles.shareBtnSecondary]} onPress={handleCopyJSON}>
                <Text style={styles.shareBtnSecondaryText}>{ '{ } Copy JSON'}</Text>
              </TouchableOpacity>
            )}
          </View>

          {/* QR code */}
          <View style={styles.qrSection}>
            <Text style={styles.qrLabel}>Scan QR for full profile</Text>
            <View style={styles.qrBox}>
              <QRDisplay data={emergencyData} />
            </View>
            <Text style={styles.qrNote}>
              Contains only emergency-relevant data. Insurance details are never included.
            </Text>
          </View>
        </>
      )}

      <View style={{ height: 40 }} />
    </ScrollView>
  );
}

function Row({ label, value, critical }) {
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={[styles.rowValue, critical && styles.rowValueCritical]}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen:   { flex: 1, backgroundColor: '#F9FAFB' },
  content:  { padding: 20 },
  loading:  { flex: 1, justifyContent: 'center', alignItems: 'center' },

  header:      { alignItems: 'center', marginBottom: 24 },
  headerBadge: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FEF2F2', alignItems: 'center', justifyContent: 'center', marginBottom: 12, borderWidth: 1, borderColor: '#FECACA' },
  headerIcon:  { fontSize: 36 },
  heading:     { fontSize: 24, fontWeight: '700', color: '#111' },
  subheading:  { fontSize: 13, color: '#6B7280', marginTop: 4 },

  emptyBox:   { backgroundColor: '#FEF9C3', borderRadius: 14, padding: 24, borderWidth: 1, borderColor: '#FDE68A', alignItems: 'center', gap: 8 },
  emptyIcon:  { fontSize: 36 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: '#92400E' },
  emptyText:  { color: '#92400E', fontSize: 14, textAlign: 'center', lineHeight: 20 },

  criticalStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  criticalPill:  { backgroundColor: '#FEF2F2', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7, borderWidth: 1, borderColor: '#FECACA' },
  criticalPillText: { fontSize: 13, fontWeight: '700', color: '#DC2626' },

  summaryBox: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#E5E7EB', overflow: 'hidden', marginBottom: 20 },
  row:        { flexDirection: 'row', justifyContent: 'space-between', padding: 14, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', gap: 12 },
  rowLabel:   { fontSize: 13, color: '#6B7280', fontWeight: '600', flex: 1 },
  rowValue:   { fontSize: 13, color: '#111', flex: 2, textAlign: 'right' },
  rowValueCritical: { color: '#DC2626', fontWeight: '700' },

  shareRow:          { flexDirection: 'row', gap: 10, marginBottom: 24 },
  shareBtn:          { flex: 1, borderRadius: 12, paddingVertical: 14, alignItems: 'center', justifyContent: 'center' },
  shareBtnPrimary:   { backgroundColor: '#DC2626' },
  shareBtnSecondary: { backgroundColor: '#fff', borderWidth: 1.5, borderColor: '#E5E7EB' },
  shareBtnDisabled:  { opacity: 0.6 },
  shareBtnText:      { color: '#fff', fontWeight: '700', fontSize: 15 },
  shareBtnSecondaryText: { color: '#374151', fontWeight: '600', fontSize: 14 },

  qrSection: { alignItems: 'center', gap: 12 },
  qrLabel:   { fontSize: 14, fontWeight: '600', color: '#374151' },
  qrBox:     { backgroundColor: '#fff', padding: 20, borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB' },
  qrNote:    { fontSize: 12, color: '#9CA3AF', textAlign: 'center', paddingHorizontal: 20 },
});
